import LayoutPage from "./../../../../components/Layouts/LayoutPage";
import LayoutBlocks from "./../../../../components/Layouts/LayoutBlocks";
import LayoutBlock from "./../../../../components/Layouts/LayoutBlock";
import Pagination from "../../../../components/Pagination";

const AdminPanelUsers = () => {
    const data = [
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
        {
            id: 1,
            create_date: "23.04.2023",
            login: "pochta@mail.ru",
            FIO: "Иванов Иван Иванович",
            phone: "+ 7 999 999-99-99",
            region: "Москва",
            balance: 2000,
            category: "Строительная материалы",
        },
    ];

    return (
        <LayoutPage title="Пользователи" isUsersTable>
            <LayoutBlocks>
                <LayoutBlock>
                    <Pagination head={["ID", "Дата регистрации", "Логин", "ФИО", "Телефон", "Регион", "Баланс", "Категория"]} items={data} itemsPerPage={5} isAdminPanelTable/>
                </LayoutBlock>
            </LayoutBlocks>
        </LayoutPage>
    );
};

export default AdminPanelUsers;
